#CONSTANTS FOR CalculatorGui.py

#Window dimensions
WINDOW_WIDTH = 420
WINDOW_HEIGHT = 240

#Button properties
BUTTON_WIDTH = 80
BUTTON_HEIGHT = 30
BIG_BUTTON_WIDTH = BUTTON_WIDTH * 4
BUTTON_FONT = 'Helvetica'
BUTTON_FONT_SIZE = 12
BUTTON_JUSTIFY = "center"
BUTTON_TEXT_COLOR = "#000000"
BUTTON_TEXT_COLOR_ONCLICK = "#189C98"
BUTTON_HIGHTLIGHTCOLOR = "#189C24"

# Window widget properties
WINDOW_WIDGET_FONT = 'Times'
WINDOW_WIDGET_FONT_SIZE = 12
WINDOW_WIDGET_JUSTIFY = "right"
WINDOW_WIDGET_WIDTH = 320
WINDOW_WIDGET_HEIGHT = 50

# Text input properties
WINDOW_TEXT_INPUT_FONT = 'Times'
WINDOW_TEXT_INPUT_FONT_SIZE = 12
WINDOW_TEXT_INPUT_JUSTIFY = "right"
WINDOW_TEXT_INPUT_WIDTH = 320
WINDOW_TEXT_INPUT_HEIGHT = 50
TEXT_RELIEFS = ('flat','groove','raised',
                'ridge','solid') # DEFAULT IS sunken
WINDOW_TEXT_INPUT_RELIEF = TEXT_RELIEFS[2]
