#CONSTANTS FOR CalculatorGui.py

#Window dimensions
WINDOW_WIDTH = 400
WINDOW_HEIGHT = 240

#Button properties
BUTTON_WIDTH = 70
BUTTON_HEIGHT = 25
BUTTON_FONT = 'Times'
BUTTON_FONT_SIZE = 12
BUTTON_JUSTIFY = "center"

# Window widget properties
WINDOW_WIDGET_FONT = 'Times'
WINDOW_WIDGET_FONT_SIZE = 12
WINDOW_WIDGET_JUSTIFY = "right"
WINDOW_WIDGET_WIDTH = 300
WINDOW_WIDGET_HEIGHT = 60
